spring:
  profiles:
    active: devops

  datasource:
    url: jdbc:mysql://${MYSQL_SQL_HOST}:${MYSQL_SQL_PORT}/${MYSQL_SQL_DB}
    username: ${MYSQL_SQL_USERNAME}
    password: ${MYSQL_SQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_TOKEN_SECRET}
  access:
    expiration-milliseconds: ${JWT_ACCESS_TOKEN_EXPIRATION}

url:
  base:
    back-end: ${BASE_URL_BACK_END}
    front-end: ${BASE_URL_FRONT_END}