# id 1
INSERT INTO `role` (name)
VALUES ('ROLE_ADMIN');
# id 2
INSERT INTO `role` (name)
VALUES ('ROLE_MANAGEMENT_EMPLOYEES');
# id 3
INSERT INTO `role` (name)
VALUES ('ROLE_MANAGEMENT_MATERIALS');
# id 4
INSERT INTO `role` (name)
VALUES ('ROLE_MANAGEMENT_PHARMACY');
