name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gestion_hopital_db
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B clean verify --file ./path/to/pom.xml

    - name: Run tests in parallel
      run: mvn -B test --file ./path/to/pom.xml --jobs 2

    - name: Notify on build failure
      if: failure()
      uses: Ilshidur/action-slack@master
      with:
        status: failure
        fields: repo,message,commit,author
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN }}

    - name: Notify on build success
      if: success()
      uses: Ilshidur/action-slack@master
      with:
        status: success
        fields: repo,message,commit,author
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_TOKEN }}

  analyze:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: gestion_hopital_db
        ports:
          - 3306:3306
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Generate code coverage report
        run: mvn jacoco:report --file ./path/to/pom.xml

      - name: Static code analysis with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=hichambouttaj_hospital-management-backend


  deploy:
    runs-on: ubuntu-latest
    needs: analyze
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Build docker image
        run: |
          docker build -t hichambouttaj/hospital_management_backend:latest .
          docker login -u hichambouttaj -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push hichambouttaj/hospital_management_backend:latest

